### ISSUE TITLE
resetOptionsStates() throws an error

### ISSUE THREAD

**Issue by jordanchang** [AlaskaAirlines/auro-menu#160]
## Describe the bug

As a developer, I want to allow our users to clear all options in an auro-menu. Per the doc, there is a method called resetOptionsStates(), but I couldn't get it to work.

## To Reproduce

1. Create an auro-menu with a few options
1. Via javascript, call resetOptionsStates()
2. A error is thrown

## Expected behavior

Should clear all options

## Screenshots

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/3304352/199795006-495880d5-a585-43c6-be5c-d36c292b2dac.png)

## Additional context

I'm basically looking for guidance on how to clear all options.

**Comment by blackfalcon** [comment]
@jordanjones243 can you take a look at this?

**Comment by jordanjones243** [comment]
@jordanchang I have investigated this issue within the code of `auro-menu`. I tested the `resetOptionsStates()` function and it seems to be working as expected. 

The `this.items is undefined` error being thrown is due to the fact that `this.items` is initialized with all existing `auro-menuoption` elements, which makes me believe it could have something to do with your implementation.

**Comment by jordanjones243** [comment]
After further investigation, this error was being thrown because the `resetOptionsStates()` was being called on `this.items` when there was no menu options in an `auro-menu`.

This issue will be closed and a new issue will be opened to reference the root bug:
- https://github.com/AlaskaAirlines/auro-menu/issues/161
