### ISSUE TITLE
Menu option needs to support optional custom/unique behavior

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-menu#35]
## Is your feature request related to a problem? Please describe.

Given the following `auro-dropdownmenu` example:

Select Address
- 555 Memory Lane
- 666 Cul de sac
- 777  Lucky Dr
- Add new address

In the cases with a defined address we would simply pass the selected value.
In the last case we would want to do something different and begin a separate work flow.

## Describe the solution you'd like

Menu options are just passing up a CustomEvent('optionSelected'). 

Setting an attribute like `customEvent="createNewAddress"` would allow for the creation of a listener to launch whatever workflow is needed and not perform the default `optionSelected` scenario.

**Comment by blackfalcon** [comment]
@jason-capsule42 is there a current request for this? I am recommending that this be pushed till the v3.1-rc.

**Comment by blackfalcon** [comment]
A use case for this is needed with the Accounts > Payments and Discounts UI. 

<img width="364" alt="Screen Shot 2022-02-28 at 3 38 03 PM" src="https://user-images.githubusercontent.com/181089/156077080-40a96b5e-f07d-4cb1-ae9a-fdf104ff7b8d.png">

To be honest, I am not sure we need to do anything to support this? Given the current HTML structure of the element... 

```html
  <auro-select>
    <auro-menu>
      <auro-menuoption value="stops">Stops</auro-menuoption>
      <auro-menuoption value="price">Price</auro-menuoption>
      <auro-menuoption value="duration">Duration</auro-menuoption>
      <auro-menuoption value="departure">Departure</auro-menuoption>
      <auro-menuoption value="arrival">Arrival</auro-menuoption>
      <auro-menuoption value="prefer alaska">Prefer Alaska</auro-menuoption>
    </auro-menu>
  </auro-select>
```

The consumer is able to easily bind an event to any option they create. E.g. 

```html
<auro-menuoption onclick="triggerCustomOption()" value="">Custom option</auro-menuoption>
```

Then this event will trigger the UI needed that corresponds to their flow. 

What is the value of supporting a custom event that they have to listen for in order to trigger the same change in the UI?
