### ISSUE TITLE
Confusion with divider reference? 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-menu#70]
# General Support Request

In the Figma file, there is a divider reference with each individual representation 

<img width="701" alt="Screen Shot 2022-01-20 at 9 32 08 AM" src="https://user-images.githubusercontent.com/181089/150391275-266cb4bb-f29e-4f29-8771-ee2461164356.png">

## Support request

There is no divider between each node in the full menu image (below). In the image above, there is an arrow pointing to the bottom of each node designating that there should be a divider line between each option? 

<img width="249" alt="Screen Shot 2022-01-20 at 9 37 46 AM" src="https://user-images.githubusercontent.com/181089/150392125-a594c09b-038f-4c9b-9189-ff07c08ded92.png">

Also, please advise as to how many dividers need to appear when there is a sub-menu. The image above shows one, but the image below shows two? 

<img width="545" alt="Screen Shot 2022-01-20 at 9 39 05 AM" src="https://user-images.githubusercontent.com/181089/150392309-c28acabd-fdf8-46be-92db-e3b6de0754f5.png">

**Comment by leeejune** [comment]
> There is no divider between each node in the full menu image (below). In the image above, there is an arrow pointing to the bottom of each node designating that there should be a divider line between each option?

The first part with a divider for each option is just for demonstration purposes. Each option COULD have a divider, but is not required. 

> Also, please advise as to how many dividers need to appear when there is a sub-menu. The image above shows one, but the image below shows two?

Dividers are completely optional. In the image above, there is just one because it is closer to what it would look like if a designer is using menu. The image below has an extra divider on the bottom just for spacing demonstration purposes.
