### ISSUE TITLE
Remove user-select: none; CSS rule from disabled menu options

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-menu#90]
## Describe the bug

Remove user-select: none; CSS rule from disabled menu options

Original issue opened in auro-select: https://github.com/AlaskaAirlines/auro-select/issues/43

**Comment by blackfalcon** [comment]
Why does this need to be removed? What is the bug this is causing?

**Comment by blackfalcon** [comment]
I don't understand why, but the PR linked to this issue is not merged in? The PR was approved and merged, but for some reason, the code is not there? 

I am taking this on as a `bug` to address the removal @jason-capsule42 as submitted, but also update all the options to have `user-select: none` as well. 

This is a UX opinion shared by Shoelace and Material UI. 

This will be released as a `patch` update.
